//! Autogenerated CPI client for the Kamino Farms program.
//!
//! CPI helpers for the [Kamino Farms](https://github.com/Kamino-Finance/kfarms)
//! program.
//!
//! This crate was automatically generated by
//! [anchor-gen](https://github.com/saber-hq/anchor-gen), a crate for generating
//! Anchor CPI helpers from JSON IDLs.

anchor_gen::generate_cpi_interface!(
    idl_path = "idl.json",
    zero_copy(
        FarmConfigOption,
        GlobalConfigOption,
        LockingMode,
        RewardInfo,
        RewardPerTimeUnitPoint,
        RewardScheduleCurve,
        RewardType,
        TimeUnit,
        TokenInfo,
        DatedPrice,
        Price,
        FarmState,
        GlobalConfig,
        UserState,
        OraclePrices,
    )
);
