//! Autogenerated CPI client for the Orca Whirlpools program.
//!
//! CPI helpers for the [Orca Whirlpools](https://github.com/orca-so/whirlpools)
//! program.
//!
//! This crate was automatically generated by
//! [anchor-gen](https://github.com/saber-hq/anchor-gen), a crate for generating
//! Anchor CPI helpers from JSON IDLs.

anchor_gen::generate_cpi_interface!(
    idl_path = "idl.json",
    zero_copy(TickArray, Tick),
    packed(TickArray, Tick)
);

impl Default for state::TickArray {
    fn default() -> Self {
        Self {
            start_tick_index: Default::default(),
            ticks: [Default::default(); 88],
            whirlpool: Default::default(),
        }
    }
}

declare_id!("whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc");
