//! Autogenerated CPI client for the Orca Whirlpools program.
//!
//! CPI helpers for the [Orca Whirlpools](https://github.com/orca-so/whirlpools)
//! program.
//!
//! This crate was automatically generated by
//! [anchor-gen](https://github.com/saber-hq/anchor-gen), a crate for generating
//! Anchor CPI helpers from JSON IDLs.

anchor_gen::generate_cpi_crate!("idl.json");

declare_id!("whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc");
