//! Autogenerated CPI client for the Kamino Lend program.
//!
//! CPI helpers for the [Kamino Lend](https://github.com/Kamino-Finance/klend)
//! program.
//!
//! This crate was automatically generated by
//! [anchor-gen](https://github.com/saber-hq/anchor-gen), a crate for generating
//! Anchor CPI helpers from JSON IDLs.

anchor_gen::generate_cpi_interface!(idl_path = "idl.json");
