//! Autogenerated CPI client for the Kamino Lend program.
//!
//! CPI helpers for the [Kamino Lend](https://github.com/Kamino-Finance/klend)
//! program.
//!
//! This crate was automatically generated by
//! [anchor-gen](https://github.com/saber-hq/anchor-gen), a crate for generating
//! Anchor CPI helpers from JSON IDLs.

#![allow(clippy::too_many_arguments)]

use anchor_lang::zero_copy;

anchor_gen::generate_cpi_interface!(
    idl_path = "idl.json",
    zero_copy(
        UpdateConfigMode,
        UpdateLendingMarketConfigValue,
        UpdateLendingMarketMode,
        LastUpdate,
        ElevationGroup,
        InitObligationArgs,
        ObligationCollateral,
        ObligationLiquidity,
        AssetTier,
        BigFractionBytes,
        FeeCalculation,
        ReserveCollateral,
        ReserveConfig,
        ReserveFarmKind,
        ReserveFees,
        ReserveLiquidity,
        ReserveStatus,
        WithdrawalCaps,
        PriceHeuristic,
        PythConfiguration,
        ScopeConfiguration,
        SwitchboardConfiguration,
        TokenInfo,
        BorrowRateCurve,
        CurvePoint,
        UserState,
        LendingMarket,
        Obligation,
        ReferrerState,
        ReferrerTokenState,
        UserMetadata,
        Reserve,
        Referrer,
        ReferrerToken,
    )
);
