use anchor_lang::prelude::*;

#[derive(AnchorSerialize, AnchorDeserialize, PartialEq, Eq, Clone, Copy, Debug)]
#[repr(u64)]
pub enum UpdateConfigMode {
    UpdateLoanToValuePct = 1,
    UpdateMaxLiquidationBonusBps = 2,
    UpdateLiquidationThresholdPct = 3,
    UpdateProtocolLiquidationFee = 4,
    UpdateProtocolTakeRate = 5,
    UpdateFeesBorrowFee = 6,
    UpdateFeesFlashLoanFee = 7,
    UpdateFeesReferralFeeBps = 8,
    UpdateDepositLimit = 9,
    UpdateBorrowLimit = 10,
    UpdateTokenInfoLowerHeuristic = 11,
    UpdateTokenInfoUpperHeuristic = 12,
    UpdateTokenInfoExpHeuristic = 13,
    UpdateTokenInfoTwapDivergence = 14,
    UpdateTokenInfoScopeTwap = 15,
    UpdateTokenInfoScopeChain = 16,
    UpdateTokenInfoName = 17,
    UpdateTokenInfoPriceMaxAge = 18,
    UpdateTokenInfoTwapMaxAge = 19,
    UpdateScopePriceFeed = 20,
    UpdatePythPrice = 21,
    UpdateSwitchboardFeed = 22,
    UpdateSwitchboardTwapFeed = 23,
    UpdateBorrowRateCurve = 24,
    UpdateEntireReserveConfig = 25,
    UpdateDebtWithdrawalCap = 26,
    UpdateDepositWithdrawalCap = 27,
    UpdateDebtWithdrawalCapCurrentTotal = 28,
    UpdateDepositWithdrawalCapCurrentTotal = 29,
    UpdateBadDebtLiquidationBonusBps = 30,
    UpdateMinLiquidationBonusBps = 31,
    UpdateDeleveragingMarginCallPeriod = 32,
    UpdateBorrowFactor = 33,
    UpdateAssetTier = 34,
    UpdateElevationGroup = 35,
    UpdateDeleveragingThresholdDecreaseBpsPerDay = 36,
    DeprecatedUpdateMultiplierSideBoost = 37,
    DeprecatedUpdateMultiplierTagBoost = 38,
    UpdateReserveStatus = 39,
    UpdateFarmCollateral = 40,
    UpdateFarmDebt = 41,
    UpdateDisableUsageAsCollateralOutsideEmode = 42,
    UpdateBlockBorrowingAboveUtilizationPct = 43,
    UpdateBlockPriceUsage = 44,
    UpdateBorrowLimitOutsideElevationGroup = 45,
    UpdateBorrowLimitsInElevationGroupAgainstThisReserve = 46,
    UpdateHostFixedInterestRateBps = 47,
    UpdateAutodeleverageEnabled = 48,
    UpdateDeleveragingBonusIncreaseBpsPerDay = 49,
}
